import fs from 'node:fs';
const read=id=>JSON.parse(fs.readFileSync(`content/${id}-advanced.json`,'utf8'));
const release=read('release'),calm=read('calm'),intent=read('intent');
// Evidence review: make the logic of the grammar tasks and interpretation precise.
release.paragraphs[7]=release.paragraphs[7].replace('Für eine glaubwürdige Ankündigung spricht daher eine einfache Anforderung:','An eine glaubwürdige Ankündigung lässt sich daher eine einfache Anforderung stellen:');
release.questions[0].question='Welche Unterschiede macht der Text zwischen Bekanntgabe, tatsächlichem Zugang und Entwicklungsstand? Erkläre, warum „veröffentlicht“ nicht automatisch „vollständig fertig“ bedeutet.';
calm.grammar.items[0].model='Tatsächlicher Bezug: „Da Mara zuvor selbst gesagt hat, sie brauche Ruhe, greift Deniz ihre eigene Bitte auf.“ Ohne eine solche Bitte: „Mara hat nicht um Ruhe gebeten; Deniz deutet ihre Stille dennoch als Wunsch nach Abstand.“ Alternative Vorgeschichte: „Hätte sie ausdrücklich um Ruhe gebeten, ließe sich seine Zurückhaltung als Rücksicht auf diese Bitte verstehen.“ Der letzte Satz sagt nicht, dass sie tatsächlich darum gebeten hat.';
intent.grammar[1].title='Konjunktiv I: eine zugeschriebene Sicht wiedergeben';
intent.registerRewrite.models[1].text=intent.registerRewrite.models[1].text.replace('erst am Donnerstag bis 18 Uhr','erst am Donnerstag um 18 Uhr');
const data={
release:{title:release.title,paragraphs:release.paragraphs,questions:release.questions,genre:'Kommentar',counterpoint:release.counterpoint},
calm:{title:calm.reading.title,paragraphs:calm.reading.paragraphs,questions:calm.reading.questions.map(q=>({paragraphs:q.paragraphs,question:q.prompt,model:q.modelDiscussion})),genre:'Kommentar'},
intent:{title:intent.reading.title,paragraphs:intent.reading.paragraphs,questions:intent.readingQuestions.map(q=>({paragraphs:q.paragraphs,question:q.question,model:q.modelDiscussion})),genre:'Kommentar'}
};
data.calm.counterpoint=[
'Ein Teammitglied hält den Vorschlag aus dem Lesetext für unnötig umständlich: „Wenn mich nach einer schwierigen Besprechung niemand fragt, wie es mir geht, empfinde ich das als Gleichgültigkeit. Ich möchte nicht jedes Mal erst erklären müssen, ob ein persönliches Gespräch gerade zulässig ist. Eine direkte Nachfrage hilft mir oft, einen Einwand überhaupt anzusprechen. Falls ich nicht reden möchte, kann ich das sagen.“',
'Eine Kollegin widerspricht: „Dass du eine Frage problemlos ablehnen kannst, heißt nicht, dass alle sich das zutrauen. Wenn die Teamleitung fragt, entsteht eine andere Situation als unter Freunden. Mir würde schon helfen, wenn meine knappe Antwort nicht als Zeichen mangelnden Vertrauens bewertet würde. Ich brauche keine besondere Formulierung, sondern die Erfahrung, dass eine Ablehnung akzeptiert wird.“',
'Die beiden Perspektiven zeigen unterschiedliche Voraussetzungen für dieselbe Regel. Eine Person setzt voraus, dass eine Frage ohne Folgen abgelehnt werden kann. Die andere möchte genau diese Voraussetzung erst herstellen. Eine Vereinbarung müsste deshalb auch das Verhalten nach einer Nachfrage berücksichtigen. Welche Beobachtung würde für die erste Person zeigen, dass Interesse besteht, und für die zweite, dass sie tatsächlich entscheiden darf? Entwickle einen Vorschlag, der beide Anliegen ernst nimmt.'
];
data.intent.counterpoint=[
'Lea findet die vorgeschlagene Rückmeldefrist sinnvoll, ist aber noch nicht zufrieden: „Ich habe die Verbindung herausgesucht und andere Pläne abgesagt. Wenn Jonas bis Donnerstag alles offenhält, kann ich zwar ohne ihn buchen. Meine Vorbereitung bleibt trotzdem bei mir. Dass niemand eine feste Zusage gemacht hat, beantwortet noch nicht die Frage, ob die Aufgaben fair verteilt waren.“',
'Jonas entgegnet: „Ich wollte mitkommen, konnte aber noch nicht wissen, ob es klappt. Hätte ich sofort Nein gesagt, hätten wir eine mögliche gemeinsame Unternehmung vorschnell ausgeschlossen. Ich kann dir allerdings anbieten, die Verbindung selbst zu recherchieren oder bis Donnerstag einen anderen Teil der Vorbereitung zu übernehmen. Eine sichere Teilnahme kann ich dir damit noch nicht versprechen.“',
'Die Klärung der ursprünglichen Nachricht beseitigt somit nicht alle Gründe für Enttäuschung. Eine Rückmeldefrist regelt Verbindlichkeit; der Umgang mit bereits geleisteter Arbeit bleibt eine weitere Frage. Beide können ihre ursprüngliche Deutung für nachvollziehbar halten und trotzdem eine neue Absprache brauchen. Welche Verantwortung folgt aus geäußertem Interesse, bevor eine feste Zusage vorliegt? Formuliere zunächst die stärkste Begründung für jede Seite. Entwickle anschließend eine Vereinbarung für den nächsten gemeinsamen Plan, die auch den Vorbereitungsaufwand berücksichtigt.'
];
data.release.thesis='Eine frühzeitige Ankündigung kann trotz Unsicherheit sinnvoll und glaubwürdig sein, sofern sie ihren vorläufigen Stand und spätere Änderungen nachvollziehbar vermittelt. Absatz 5 begründet den Nutzen früher Information; Absatz 6 begrenzt dieses Argument durch die Verantwortung für selbst geweckte Erwartungen.';
data.calm.thesis='Die Angemessenheit einer Nachfrage hängt von Gesprächsvorgeschichte, Beziehung und tatsächlichem Antwortspielraum ab. Absatz 7 begrenzt die scheinbar einfache Lösung, jede Formulierung möglichst stark abzuschwächen: Auch Direktheit und die klare Benennung des eigenen Anliegens können rücksichtsvoll sein.';
data.intent.thesis='Interesse und Unsicherheit sollten so ausgedrückt werden, dass andere daraus keine unbeabsichtigte Zusage ableiten. Absatz 4 begrenzt zugleich den Anspruch auf sofortige Klarheit: Fehlen wesentliche Informationen, kann eine sofortige Entscheidung nicht sinnvoll verlangt werden.';
const qaModel=entry=>entry.questions.map((q,i)=>`${i+1}. ${q.model}`).join('\n\n');
const article=(d,source)=>({title:d.title,kicker:'Lesen · Argumentation',kind:'article',genre:d.genre,paragraphs:d.paragraphs,question:'Welche Position entwickelt der Text, und an welcher Stelle wird sie eingeschränkt?',coach:'Lies zunächst den ganzen Text. Formuliere die Hauptaussage in zwei Sätzen und nenne einen Absatz, der eine einfache Antwort verhindert.',prompt:'Hauptaussage und Textbeleg',model:d.thesis,source,extension:{title:'Eine Annahme prüfen',task:'Welche Voraussetzung wird im Text nicht ausdrücklich begründet? Entwickle einen Fall, in dem sie nicht zutrifft, und präzisiere die Schlussfolgerung entsprechend.'}});
const closeReading=(d,source)=>({title:'Den Gedankengang untersuchen',kicker:'Lesen · Deuten und belegen',kind:'analysis',lead:'Begründe deine Antworten mit konkreten Textstellen. Eine andere plausible Deutung ist möglich, wenn du sie am Text zeigen kannst.',tasks:d.questions,reference:d.paragraphs,question:'Welche Antwort braucht eine Einschränkung, damit sie den Text genau wiedergibt?',coach:'Besprecht die vier Fragen nacheinander. Halte zu jeder Antwort eine Textstelle und deine Schlussfolgerung fest.',prompt:'Antworten 1–4 mit Absatzbelegen',model:qaModel(d),source});
const perspectives=(d,source)=>({title:'Eine weitere Perspektive',kicker:'Lesen · Positionen vergleichen',kind:'article',genre:'Zwei Reaktionen auf den Lesetext',paragraphs:d.counterpoint,question:'Welche Frage bleibt nach dem Ausgangstext offen? Entwickle eine begründete Antwort.',coach:'Gib beide Positionen so wieder, dass die jeweilige Person zustimmen könnte. Trenne anschließend Zustimmung, Einwand und eigenen Vorschlag.',prompt:'Vergleich und eigene Position',source,reference:d.paragraphs,extension:{title:'Synthese in 90 Wörtern',task:'Verbinde beide Reaktionen und den Ausgangstext in einer eigenen Position. Übernimm keine Formulierung wörtlich und mache eine verbleibende Unsicherheit deutlich.'}});
const updates={};
for(const [id,d]of Object.entries(data))updates[id]={start:'reading',reading:[article(d,'reading_advanced'),closeReading(d,'reading_advanced'),perspectives(d,'reading_advanced')]};
updates.release.goal='Ankündigungen einordnen, Verbindlichkeit beurteilen und Änderungen präzise erklären.';
updates.calm.goal='Vorannahmen, Rollen und Tonfall erkennen und ein Gespräch passend eröffnen.';
updates.intent.goal='Interesse, Unsicherheit und Zusagen unterscheiden und Missverständnisse klären.';
updates.release.vocabularyExtra=[{title:'Erwartungen und Verbindlichkeit',kicker:'Wortschatz · Im Lesetext',kind:'words',lead:'Erkläre, welche Verbindung die Verantwortung einer Person hervorhebt und welche eine Unsicherheit beschreibt.',words:[['mit einer Nachfrage rechnen','etwas als wahrscheinlich erwarten · Absatz 3','Der Verlag muss abschätzen, mit welcher Nachfrage zu rechnen ist.'],['einen Vorbehalt äußern','eine Einschränkung deutlich machen · Absatz 4','Der Vorbehalt wird erst im Kleingedruckten sichtbar.'],['eine Erwartung nahelegen','eine Erwartung entstehen lassen · Absatz 6','Mit dem festen Datum hat der Verlag eine klare Erwartung nahegelegt.'],['sich auf etwas zurückziehen','eine frühere Position als Schutz verwenden · Absatz 6','Der Verlag zieht sich auf die Unverbindlichkeit der Ankündigung zurück.']],question:'Wie unterscheiden sich „eine Erwartung wecken“, „etwas nahelegen“ und „etwas zusagen“?',coach:'Beziehe dich auf den Verlag. Welche Formulierung behauptet bereits eine Verpflichtung?',prompt:'Abstufungen mit eigenen Beispielen',source:'vocabulary'},
{title:'Einen Einwand begrenzen',kicker:'Wortschatz · Präzision',kind:'words',words:[['etwas nur unzureichend berücksichtigen','einen relevanten Gesichtspunkt zu wenig beachten · Absatz 5','Die Kritik berücksichtigt die redaktionelle Arbeit nur unzureichend.'],['von etwas auf etwas schließen','aus einer Beobachtung eine Folgerung ziehen · Absatz 7','Aus der Verfügbarkeit lässt sich nicht auf den vollständigen Funktionsumfang schließen.'],['etwas gesondert beschreiben','zwei Fragen ausdrücklich auseinanderhalten · Absatz 7','Der Entwicklungsstand muss gesondert beschrieben werden.'],['eine Entscheidung auf etwas stützen','eine Information als Entscheidungsgrundlage verwenden · Absatz 8','Die Buchhandlung stützt ihre Planung auf den angekündigten Termin.']],question:'Widersprich dem Satz „Wenn ein Produkt verfügbar ist, ist es fertig“, ohne die Behauptung pauschal abzutun.',coach:'Verwende zwei Verbindungen aus dieser Seite und ein konkretes Gegenbeispiel.',prompt:'Begründeter Widerspruch',source:'vocabulary'}];
updates.calm.vocabularyExtra=[0,1].map(part=>({title:part?'Anliegen und Vorannahmen':'Deutungen sprachlich erkennen',kicker:'Wortschatz · Im Lesetext',kind:'words',lead:calm.vocabulary.instruction,words:calm.vocabulary.items.slice(part*4,part*4+4).map(w=>[w.expression,`Absatz ${w.paragraph} · ${w.meaning}`,w.contrast]),question:calm.vocabulary.items[part*4].transferPrompt,coach:'Erkläre die Verbindung in ihrem Absatz und verwende sie anschließend in einem anderen Kontext.',prompt:'Eigene Beispiele und Bedeutungsunterschiede',source:'vocabulary'}));
updates.intent.vocabularyExtra=[0,1].map(part=>({title:part?'Verbindlichkeit und Deutung':'Handlungsspielraum und Rücksicht',kicker:'Wortschatz · Im Lesetext',kind:'words',words:intent.collocations.slice(part*4,part*4+4).map(w=>[w.phrase,`Absatz ${w.paragraph} · ${w.meaning}`,w.textAnchor]),question:intent.collocations[part*4].practice,coach:'Prüfe, ob die Verbindung neutral beschreibt oder bereits eine Bewertung enthält. Bilde anschließend eigene Sätze.',prompt:'Verwendung im eigenen Kontext',source:'vocabulary'}));
updates.release.grammar=[{title:'Planung oder fremde Aussage?',kicker:'Grammatik · Modalverb „sollen“',kind:'pattern',lead:'Die Lesart hängt vom Zusammenhang ab. „Sollen“ ist nicht automatisch ein Unsicherheitsmarker mit nur einer Bedeutung.',patterns:[['Laut Verlagsprogramm soll das Buch im Oktober erscheinen.','Der Zusammenhang legt eine Planung nahe; je nach Kontext kann zugleich eine Quellenangabe vorliegen.'],['Das Buch soll bereits vergriffen sein; die Buchhandlung konnte es noch nicht bestätigen.','Hier wird eine nicht selbst bestätigte Information wiedergegeben.'],['Der Verlag erklärt, das Buch erscheine im Oktober.','Konjunktiv I kennzeichnet die wiedergegebene Aussage. Er garantiert weder ihre Wahrheit noch ihren Irrtum.']],question:'Gib die Terminangabe einmal als Plan und einmal als unbestätigte Information wieder. Mache die jeweilige Lesart im Kontext eindeutig.',coach:'Besprecht, welche Information aus dem Verb und welche erst aus dem Zusammenhang entsteht.',prompt:'Zwei Kontexte und eine Begründung',model:'Planung: „Die Redaktion arbeitet auf Oktober hin; für diesen Monat ist die Veröffentlichung vorgesehen.“ Unbestätigte Information: „Nach Angaben eines Händlers soll das Buch schon ausgeliefert worden sein. Der Verlag hat uns dazu noch keine Auskunft gegeben.“',source:'grammar'},
{title:'Einen Einwand einräumen und begrenzen',kicker:'Grammatik · Konzessive Beziehungen',kind:'pattern',patterns:[['Obwohl der Termin verschoben wurde, kann die Ankündigung glaubwürdig bleiben.','„Obwohl“ räumt eine tatsächliche Voraussetzung ein, die gegen die Schlussfolgerung sprechen könnte.'],['Selbst wenn der Termin erneut verschoben würde, wäre damit noch keine Täuschungsabsicht belegt.','„Selbst wenn“ führt hier einen hypothetischen Grenzfall ein.'],['Zwar war die Verzögerung sachlich begründet, doch wurde sie dem Handel zu spät mitgeteilt.','„Zwar … doch“ gewichtet zwei gleichzeitig geltende Aussagen.']],question:'Formuliere mit „zwar … doch“ einen berechtigten Einwand gegen den Verlag. Übertrage ihn anschließend in einen hypothetischen Fall mit „selbst wenn“.',coach:'Verändere die Aussageabsicht bewusst. Ein bloßer Austausch der Konnektoren genügt nicht.',prompt:'Zwei Formulierungen mit Bedeutungsunterschied',model:'„Zwar braucht die Überarbeitung Zeit, doch hätte der Verlag früher informieren können.“ / „Selbst wenn die Überarbeitung länger dauern würde, könnte der Verlag einen verlässlichen nächsten Informationszeitpunkt nennen.“',source:'grammar'}];
updates.calm.grammar=calm.grammar.items.map(g=>({title:g.title,kicker:`Grammatik · Absatz ${g.paragraph}`,kind:'pattern',patterns:[[g.quote,g.function]],question:g.task,coach:'Erkläre zuerst, welche Bedeutung die Form im Text trägt. Prüfe dann, was sich durch die Umformulierung verändert.',prompt:'Umformulierung und Bedeutungsunterschied',model:g.model,source:'grammar'}));
updates.intent.grammar=intent.grammar.map(g=>({title:g.title,kicker:`Grammatik · Absatz ${g.paragraph}`,kind:'pattern',patterns:[[g.quote,g.notice]],question:g.task,coach:'Beziehe die Form auf den Gedankengang des Textes. Eine grammatisch mögliche Alternative kann eine andere Perspektive hervorheben.',prompt:'Eigene Formulierungen',model:g.model,source:'grammar'}));
updates.release.expressionExtra=[{title:'Eine Verschiebung erklären',kicker:'Ausdruck · Register und Verantwortung',kind:'tone',lead:'Der Roman war für Oktober angekündigt. Die Überarbeitung dauert länger. Ein neuer Erscheinungstermin ist noch offen; am 15. November folgt eine weitere Mitteilung.',original:'Das Buch kommt halt später. Es war ja nur angekündigt.',tones:[['public','An die Leserschaft','Die Überarbeitung benötigt mehr Zeit als vorgesehen. Der Roman wird deshalb nicht im Oktober erscheinen. Einen neuen Termin können wir noch nicht verlässlich nennen; am 15. November informieren wir über den Stand.','Benennt Änderung, Grund und nächsten Informationszeitpunkt. Ein neuer Veröffentlichungstermin wird nicht erfunden.'],['partner','An die Buchhandlung','Uns ist bewusst, dass Sie Ihre Planung auf den angekündigten Termin gestützt haben. Leider müssen wir die Veröffentlichung verschieben. Bitte planen Sie vorerst keine Veranstaltung mit festem Erscheinungsdatum; am 15. November erhalten Sie eine neue Rückmeldung.','Greift die praktische Folge für den Adressaten auf. Die Beziehung und die benötigte Information beeinflussen die Formulierung.'],['informal','Im Gespräch','Das Buch wird im Oktober noch nicht fertig. Die Redaktion braucht länger als gedacht. Wann es erscheint, steht noch nicht fest; Mitte November gibt’s ein Update.','Informeller Wortschatz erhält dieselben wesentlichen Informationen. Direkte Sprache muss die Verantwortung nicht verschleiern.']],question:'Welche Formulierung würde eine Erklärung in eine Ausrede verwandeln? Überarbeite den Ausgangssatz für einen konkreten Adressaten.',coach:'Erhalte den Grad der Gewissheit. Kennzeichne, was feststeht und was noch offen ist.',prompt:'Eigene Mitteilung',source:'register'}];
updates.calm.expressionExtra=[{title:calm.expression.title,kicker:'Ausdruck · Register übertragen',kind:'reading',paragraphs:[calm.expression.situation,calm.expression.task],question:calm.expression.comparisonPrompt,coach:'Schreibe zuerst eine eigene Fassung. Vergleiche danach mit den Beispielen auf der nächsten Seite.',prompt:'Drei adressatengerechte Fassungen',source:'register'},
{title:'Drei mögliche Fassungen vergleichen',kicker:'Ausdruck · Wirkung begründen',kind:'phrases',phrases:calm.expression.models.map(m=>[m.register,m.text,m.discussion]),question:'Welche Grenze bleibt in allen Fassungen bestehen, und welche Annahme verändert sich?',coach:'Die Beispiele sind Möglichkeiten. Begründe eine Alternative, wenn sie in deiner Situation besser passt.',prompt:'Vergleich mit meiner Fassung',source:'register'}];
updates.intent.expressionExtra=[{title:intent.registerRewrite.title,kicker:'Ausdruck · Beziehung und Verbindlichkeit',kind:'reading',paragraphs:[intent.registerRewrite.source,intent.registerRewrite.intention,intent.registerRewrite.task],question:'Wie verhinderst du, dass Freundlichkeit als feste Zusage verstanden wird?',coach:'Entwirf beide Fassungen. Die nächste Seite bietet Vergleichsbeispiele.',prompt:'Nachricht an Freundin und Kollegen',criteria:intent.registerRewrite.selfCheck,source:'register'},
{title:'Formulierungen vergleichen',kicker:'Ausdruck · Register begründen',kind:'phrases',phrases:intent.registerRewrite.models.map(m=>[m.audience,m.text,m.discussion]),question:'Welche Unterschiede entstehen durch die Beziehung, welche durch den Informationsbedarf?',coach:'Begründe mindestens eine Änderung an deiner eigenen Fassung.',prompt:'Meine überarbeitete Formulierung',source:'register'}];
updates.release.speaking=[{title:'Ein neuer Termin ist noch offen',kicker:'Sprechen · Verhandeln',kind:'dialogue',lines:[['Verlag','Die Überarbeitung des Romans ist noch nicht abgeschlossen. Du möchtest Vertrauen erhalten, kannst aber keinen verlässlichen neuen Termin nennen. Eine öffentliche Aktualisierung ist erst in zwei Wochen möglich.'],['Buchhandel','Du hast eine Lesung angekündigt und einen Raum reserviert. Bis morgen musst du entscheiden, ob du sie absagst. Du brauchst eine belastbare Auskunft, keine weitere allgemeine Zusicherung.']],question:'Welche Vereinbarung ist möglich, obwohl der Erscheinungstermin unklar bleibt?',coach:'Kläre zuerst den Informationsbedarf der anderen Rolle. Vereinbart einen nächsten Schritt, eine zuständige Person und eine Rückmeldefrist.',prompt:'Vereinbarung und offene Punkte',criteria:['Ein berechtigter Einwand der anderen Rolle wurde in eigenen Worten wiedergegeben.','Die Lösung enthält keine erfundene Gewissheit.','Eine konkrete Entscheidung ist jetzt möglich.'],source:'speaking'},
{title:'Den Einwand der anderen Seite vertreten',kicker:'Sprechen · Perspektivwechsel',kind:'reading',paragraphs:['Tauscht die Rollen. Die Buchhandlung erfährt nun, dass eine kurzfristige Absage Gebühren verursacht. Der Verlag erfährt, dass ein Auszug für die Veranstaltung verfügbar wäre, aber nicht das ganze Buch.'],question:'Wie verändert die neue Information eure Vereinbarung?',coach:'Begründe, welche Teile der ersten Vereinbarung weiterhin gelten. Fasse anschließend die verbleibende Differenz zusammen, ohne der anderen Seite schlechte Absichten zu unterstellen.',prompt:'Überarbeitete Vereinbarung',source:'speaking'}];
updates.calm.speaking=[{title:calm.speaking.title,kicker:'Sprechen · Zwei berechtigte Anliegen',kind:'dialogue',lead:calm.speaking.setup,lines:[[calm.speaking.roleA.name,calm.speaking.roleA.goal+' '+calm.speaking.roleA.constraint],[calm.speaking.roleB.name,calm.speaking.roleB.goal+' '+calm.speaking.roleB.constraint]],question:'Welche Regel schützt Entscheidungsfreiheit und ermöglicht zugleich die notwendige Zusammenarbeit?',coach:calm.speaking.sequence.slice(0,3).join(' '),prompt:'Gemeinsame Vereinbarung',criteria:calm.speaking.successCriteria,source:'speaking'},
{title:'Die Vereinbarung unter Zeitdruck prüfen',kicker:'Sprechen · Rollenwechsel',kind:'reading',paragraphs:['Die Sachentscheidung muss in einer Stunde getroffen werden. Ein Teammitglied hat das Angebot zu einem persönlichen Gespräch abgelehnt, zur Aufgabenverteilung aber noch nicht geantwortet.'],question:'Wie fragst du nach, ohne die beiden Anliegen wieder zu vermischen?',coach:'Tauscht die Rollen. Formuliert eine Nachricht und prüft ihre Voraussetzung, Verbindlichkeit und mögliche Wirkung.',prompt:'Nachfrage unter veränderten Bedingungen',source:'speaking'}];
updates.intent.speaking=[{title:intent.roleplay.title,kicker:'Sprechen · Verbindlichkeit aushandeln',kind:'dialogue',lead:intent.roleplay.scenario,lines:[['Teilnahme',intent.roleplay.learnerRole],['Organisation',intent.roleplay.teacherRole]],question:'Welche Zusage ist heute möglich, und wer trägt die Folgen der verbleibenden Unsicherheit?',coach:intent.roleplay.rounds.slice(0,2).join(' '),prompt:'Lösung und verbleibender Konflikt',criteria:intent.roleplay.successCriteria,source:'speaking'},
{title:'Den Stand gemeinsam wiedergeben',kicker:'Sprechen · Eine Vereinbarung formulieren',kind:'reading',paragraphs:[intent.roleplay.rounds[2]],question:'Können beide Rollen dieselbe Nachricht unterschreiben, ohne ihre Position falsch wiedergegeben zu sehen?',coach:'Tauscht die Rollen und prüft die gemeinsame Nachricht. Benennt eine Formulierung, die mehr verspricht, als vereinbart wurde.',prompt:'Gemeinsame Nachricht',source:'speaking'}];
const writingCriteria={release:['Wird zwischen Ankündigung, Zugang und fertigem Entwicklungsstand unterschieden?','Beantwortest du einen berechtigten Einwand gegen deine Position?','Stützt ein konkretes Beispiel die Argumentation?','Bleibt klar, was gesichert ist und was nur geplant wird?','Ist der vorgeschlagene nächste Schritt für einen bestimmten Adressaten praktisch brauchbar?','Ersetze eine pauschale Bewertung durch eine begründete Einschränkung.'],calm:calm.writing.revisionCriteria.map(c=>`${c.criterion}: ${c.check}`),intent:intent.writing.revisionCriteria};
const writingPrompt={release:'Schreibe einen Beitrag von 250–320 Wörtern für das Branchenforum einer Buchhandlung. Ein Verlag hat ein lange angekündigtes Buch verschoben. Einige Mitglieder fordern, künftig nur noch fertige Werke anzukündigen. Nimm begründet Stellung. Unterscheide frühe Information, verbindliche Zusage und tatsächliche Verfügbarkeit. Gehe auf einen berechtigten Einwand gegen deine eigene Position ein und entwickle eine konkrete Regel für den Umgang mit vorläufigen Terminen. Nutze mindestens einen Gedanken aus dem Lesetext in eigenen Worten.',calm:calm.writing.prompt,intent:intent.writing.prompt};
for(const id of Object.keys(data))updates[id].writing=[{title:id==='release'?'Wie verbindlich ist eine Ankündigung?':id==='calm'?calm.writing.title:intent.writing.title,kicker:'Schreiben · Begründet Stellung nehmen',kind:'writing',lead:writingPrompt[id],question:'Was ist deine Position, und welchen berechtigten Einwand musst du beantworten?',coach:'Plane zuerst These, Beispiel, Gegenargument und Vorschlag. Überarbeite anschließend mit deiner Lehrkraft. Der Wortumfang ist ein Richtwert.',prompt:'Dein Beitrag',targetWords:'250–320',criteria:writingCriteria[id],source:'writing',extension:{title:'Für einen anderen Adressaten schreiben',task:'Übertrage deine Schlussfolgerung anschließend in eine Nachricht von 70–90 Wörtern an eine konkret betroffene Person. Bewahre die nötigen Einschränkungen, ohne den ganzen Gedankengang zu wiederholen.'}},
{title:'Die eigene Argumentation überarbeiten',kicker:'Schreiben · Präzision und Aufbau',kind:'writing',reuse:`v2:${id}:writing:0`,lead:'Dein erster Entwurf bleibt unten sichtbar. Lies ihn mit deiner Lehrkraft und markiere eine inhaltliche und eine sprachliche Änderung, die du vornehmen möchtest.',question:'Welche Aussage braucht einen Beleg oder eine Einschränkung? Welche Formulierung erzeugt eine unbeabsichtigte Deutung?',coach:'Schreibe eine überarbeitete Fassung. Erkläre anschließend mündlich, wie die beiden Änderungen die Wirkung oder Genauigkeit verbessern.',prompt:'Überarbeiteter Beitrag',targetWords:'250–320',criteria:writingCriteria[id],source:'writing'}];
// All generated activities get stable revision keys. Earlier drafts remain in the notebook.
const output=`/* Generated from the advanced content packets by scripts/build-content.mjs. */\n(()=>{\nconst updates=${JSON.stringify(updates,null,2)};\nfor(const [id,update] of Object.entries(updates)){const lesson=window.LESSONS[id];const vocabulary=[...lesson.vocabulary,...update.vocabularyExtra];const expression=[...update.expressionExtra,...lesson.expression];Object.assign(lesson,update,{vocabulary,expression});delete lesson.vocabularyExtra;delete lesson.expressionExtra;for(const area of ['reading','vocabulary','grammar','expression','speaking','writing'])lesson[area].forEach((page,i)=>{page.id='v2:'+id+':'+area+':'+i;if(area==='speaking')page.lang='de';});}\nwindow.SOURCE_PATTERNS.reading_advanced={file:'C1_1065R_DE',title:'Die Zukunft der Bibliothek',pages:'7–9, 13–15, 20–25',volume:'C1.1',note:'A sustained reading develops competing perspectives, followed by interpretation and discussion. The new topics and all their wording are original. A sample of eight source readings measured 460–957 words; this is a corpus comparison, not a level requirement.'};\nwindow.SOURCE_PATTERNS.writing.note='Planning an argument, comparing approaches, revising and transferring ideas. The 250–320-word assignments in this demo are original adaptations.';\n})();\n`;
fs.writeFileSync('dist/advanced-lessons.js',output);
for(const [id,d]of Object.entries(data))console.log(`${id}: ${d.paragraphs.join(' ').split(/\s+/).length} words, ${d.questions.length} interpretation questions`);
